In [3]:
import numpy as np
import pandas as pd
np.random.seed(1)
pd.read_csv()

In [2]:
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [3]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
B.shape

(4, 1)

In [14]:
a = np.random.randn(3, 4)
b = np.random.randn(4, 1)
c = np.random.randn(3, 4)
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
print(c)

[[-0.62549001  0.91733029  1.21701734 -1.44164799]
 [ 0.89679702 -0.45750112 -1.19692257 -0.84134097]
 [-1.00505084  1.88599648 -0.83499959 -1.41352064]]


In [19]:
a + b.T

array([[-0.62549001,  0.91733029,  1.21701734, -1.44164799],
       [ 0.89679702, -0.45750112, -1.19692257, -0.84134097],
       [-1.00505084,  1.88599648, -0.83499959, -1.41352064]])

In [10]:
0.07080762*-0.3769458

-0.026690634966996002

In [2]:
matrix = np.random.randn(6,6)
print(matrix)
upper_matrix= np.triu(matrix)
diag_matrix = np.diag(np.diag(upper_matrix))
A = upper_matrix - diag_matrix

[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944 -1.09989127 -0.17242821 -0.87785842]
 [ 0.04221375  0.58281521 -1.10061918  1.14472371  0.90159072  0.50249434]
 [ 0.90085595 -0.68372786 -0.12289023 -0.93576943 -0.26788808  0.53035547]
 [-0.69166075 -0.39675353 -0.6871727  -0.84520564 -0.67124613 -0.0126646 ]]


In [3]:
for i in range(3):
    result = np.linalg.matrix_power(A,i)
    print(result)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[ 0.         -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387 ]
 [ 0.          0.          0.3190391  -0.24937038  1.46210794 -2.06014071]
 [ 0.          0.          0.         -1.09989127 -0.17242821 -0.87785842]
 [ 0.          0.          0.          0.          0.90159072  0.50249434]
 [ 0.          0.          0.          0.          0.          0.53035547]
 [ 0.          0.          0.          0.          0.          0.        ]]
[[ 0.          0.         -0.19517421  0.73348542 -1.77076075  1.64377732]
 [ 0.          0.          0.         -0.35090832 -0.27984136  0.37005858]
 [ 0.          0.          0.         -0.         -0.99165176 -0.64413738]
 [ 0.          0.          0.          0.          0.          0.47816357]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.      

In [6]:
m = 7
n = 5
A = np.random.randint(10,size= (m,n))
r,s = 3,2
print(A)
A1= A[r:,s:]
print(A1)
print(A1.shape)
trans_A = np.transpose(A)
B1 =trans_A[s:,r:]
np.array_equal(A1.T,B1)

[[8 9 5 7 0]
 [9 3 9 1 4]
 [4 6 8 8 9]
 [2 7 5 5 4]
 [5 8 5 8 1]
 [1 8 7 0 3]
 [4 2 0 3 5]]
[[5 5 4]
 [5 8 1]
 [7 0 3]
 [0 3 5]]
(4, 3)


True

In [10]:
n = 5
A = np.random.randint(10,size= (n,n))
sym_matrix = (A + A.T)/2
print(sym_matrix)

[[5.  4.5 8.5 7.  1. ]
 [4.5 7.  7.  6.5 5. ]
 [8.5 7.  2.  6.  3. ]
 [7.  6.5 6.  7.  6. ]
 [1.  5.  3.  6.  2. ]]
