In [11]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
tf.reset_default_graph()
x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2

In [2]:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

In [3]:
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)
print(result)

42


In [4]:
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()
print(result)

42


In [5]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run() # actually initialize all variables
    result = f.eval()

In [6]:
sess = tf.InteractiveSession()
init.run()
result = f.eval()
print(result)
sess.close()
print(result)

42
42


In [7]:
x1 = tf.Variable(1)
x1.graph is tf.get_default_graph()

graph = tf.Graph()

with graph.as_default():
    x2 = tf.Variable(2)
print(x2.graph is graph)
print(x2.graph is tf.get_default_graph())

True
False


In [8]:
w = tf.constant(3)
x = w + 2
y = x + 5
z = x*3
with tf.Session() as sess:
    print(y.eval())
    print(z.eval())
with tf.Session() as sess:
    y_val, z_val = sess.run([y,z])
    print(y_val)
    print(z_val)

10
15
10
15


In [9]:
housing = fetch_california_housing()
m,n = housing.data.shape
print(m,n)
housing_data_plus_bias = np.c_[np.ones((m,1)),housing.data]
X = tf.constant(housing_data_plus_bias,dtype= tf.float32,name = 'X')
y = tf.constant(housing.target.reshape(-1,1),dtype = tf.float32, name = 'y')
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)
with tf.Session() as sess:
    theta_eval = theta.eval()

20640 8


In [12]:
standard_scaler = StandardScaler()
n_epochs = 1000
learning_rate = 0.01
scaled_housing_data_plus_bias = standard_scaler.fit_transform(housing_data_plus_bias)
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)

    best_theta = theta.eval()

Epoch 0 MSE = 9.095665
Epoch 100 MSE = 5.0239
Epoch 200 MSE = 4.9196787
Epoch 300 MSE = 4.8933706
Epoch 400 MSE = 4.8744264
Epoch 500 MSE = 4.8597813
Epoch 600 MSE = 4.8483505
Epoch 700 MSE = 4.8393893
Epoch 800 MSE = 4.8323183
Epoch 900 MSE = 4.8267198


In [13]:
standard_scaler = StandardScaler()
n_epochs = 1000
learning_rate = 0.01
scaled_housing_data_plus_bias = standard_scaler.fit_transform(housing_data_plus_bias)
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)

    best_theta = theta.eval()

Epoch 0 MSE = 12.524676
Epoch 100 MSE = 5.003911
Epoch 200 MSE = 4.8493657
Epoch 300 MSE = 4.832482
Epoch 400 MSE = 4.8250585
Epoch 500 MSE = 4.81984
Epoch 600 MSE = 4.815957
Epoch 700 MSE = 4.813032
Epoch 800 MSE = 4.810819
Epoch 900 MSE = 4.8091416


In [21]:
A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A: [[4, 5, 6], [7, 8, 9]]})

In [27]:
A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: np.array([[1,2,3]])})
    B_val_2 = B.eval(feed_dict={A: np.array([[4, 5, 6], [7, 8, 9]])})
print(B_val_1)
print(B_val_2)

[[6. 7. 8.]]
[[ 9. 10. 11.]
 [12. 13. 14.]]
