In [2]:
import pandas as pd
import numpy as np
from scipy.special import softmax
np.random.seed(1)

In [3]:
a = np.random.rand(5)
print(np.exp(a)/np.sum(np.exp(a)))
print(softmax(a))

[0.21421417 0.29011541 0.14118466 0.19100257 0.16348319]
[0.21421417 0.29011541 0.14118466 0.19100257 0.16348319]


In [19]:
print(a_2)
print(a_3)
print(a_4)

[[0.15226494 0.16652095]
 [0.11456283 0.22613258]
 [0.17051192 0.17000679]]
[[0.34816173 0.29595289]
 [0.26195388 0.40189893]
 [0.38988439 0.30214818]]
[[0.47764016 0.52235984]
 [0.33626173 0.66373827]
 [0.5007417  0.4992583 ]]


In [25]:
a_4.sum(axis=1)

array([1., 1., 1.])

In [16]:
a_1 = np.random.rand(3,2)
a_2 = softmax(a_1)
a_3 = softmax(a_1,axis=0)
a_4 = softmax(a_1,axis=1)