In [19]:
import numpy as np
import scipy
from math import sqrt

## Chapter2
- Exercise 2

In [22]:
a = np.array([[4,2,4],[2,2,2],[4,2,9]])
print(a)
L = scipy.linalg.cholesky(a)

[[4 2 4]
 [2 2 2]
 [4 2 9]]


In [23]:
L

array([[2.        , 1.        , 2.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 2.23606798]])