In [1]:
import numpy as np
import scipy
from math import sqrt
np.set_printoptions(precision=3)

## Chapter2
- Exercise 2

In [9]:
a = np.array([2,0,-1, 1])
1/sqrt(6) * a
u2 = np.array([1,2,0,3])
t=np.linalg.norm(u2 - 2.04 * np.array([0.816, 0, -0.408, 0.408]))

In [10]:
(u2 - 2.04 * np.array([0.816, 0, -0.408, 0.408]))/t

array([-0.212,  0.638,  0.265,  0.691])

In [18]:
u3 = np.array([3,0,-1,2])
v1 = np.array([0.816,0,-0.408,0.408])
v2 = np.array([-0.212,0.638,0.265,0.691])
v3 = u3 - 3.672*v1 - 0.481*v2
v3/np.linalg.norm(v3)

array([ 0.203, -0.589,  0.711,  0.325])

In [28]:
t1 = np.array([0.33,0.64,0.96])
t2 = np.array([1.64,-0.59,1.05])
0.59*t1 + 0.64*t2

array([1.244, 0.   , 1.238])

In [27]:
1.22*-0.5 + 0.59 *0.5 +1.03*0.5

0.2

In [ ]:
+