In [1]:
import numpy as np
import scipy
from math import sqrt
import sympy as sp
np.set_printoptions(precision=3)

### Chapter 2

In [2]:

##### Exercise 2
try:
    A = np.array(([4,2,4],[2,2,2],[4,2,3]))
    L= np.linalg.cholesky(A)
except Exception as e: 
    print(e)


Matrix is not positive definite


### Chapter 3

In [3]:

def gram_schmidt_ortho(U):
    '''
    Input arr: array whose gram schmidt orthogonalization needs to be done
    return G : Gram schmidt 
    '''
    row,col = U.shape
    V = U/np.linalg.norm(U,axis=0)
    G = np.zeros([row,col])
    for i in range(col):
        G[:,i]= U[:,i] - np.sum(G[:,:i].T.dot(U[:,i].reshape(row,1)).T.repeat(row,axis =0) * G[:,:i],axis = 1)
        G[:,i] = G[:,i]/np.linalg.norm(G[:,i])
    return G
A = np.array([[2,0,-1,1],[1,2,0,3],[3,0,-1,2]])
print(gram_schmidt_ortho(A.T))


[[ 0.816 -0.213  0.195]
 [ 0.     0.638 -0.586]
 [-0.408  0.266  0.716]
 [ 0.408  0.691  0.325]]


### Chapter 4

In [7]:
Q = sp.Matrix([[3,2,-1,4,1],[0,1,-1,2,2],[1,-3,0,1,2],[4,-3,1,1,-1]])
A = Q.rref()
print(A)
x0, x1, x2, x3, x4 = sp.symbols('x0, x1, x2, x3, x4')
b = sp.Matrix([15,11,11,4])
system = A, b = Q,b
c=sp.linsolve(system, x0, x1, x2, x3, x4)
print(c)

(Matrix([
[1, 0, 0,   7/10,  -1/10],
[0, 1, 0,  -1/10,  -7/10],
[0, 0, 1, -21/10, -27/10],
[0, 0, 0,      0,      0]]), (0, 1, 2))
FiniteSet((-7*x3/10 + x4/10 + 23/10, x3/10 + 7*x4/10 - 29/10, 21*x3/10 + 27*x4/10 - 139/10, x3, x4))


In [8]:
0.92*100 + 0.8*9

99.2