In [1]:
# import os
# import sys
# import tarfile
# import time

# source = 'http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz'
# target = 'aclImdb_v1.tar.gz'

# def reporthook(count, block_size, total_size):
#     global start_time
#     if count == 0:
#         start_time = time.time()
#         return
#     duration = time.time() - start_time
#     progress_size = int(count * block_size)
#     speed = progress_size / (1024.**2 * duration)
#     percent = count * block_size * 100. / total_size
#     sys.stdout.write("\r%d%% | %d MB | %.2f MB/s | %d sec elapsed" %
#                     (percent, progress_size / (1024.**2), speed, duration))
#     sys.stdout.flush()

# if not os.path.isdir('aclImdb') and not os.path.isfile('aclImdb_v1.tar.gz'):
    
#     if (sys.version_info < (3, 0)):
#         import urllib
#         urllib.urlretrieve(source, target, reporthook)
    
#     else:
#         import urllib.request
#         urllib.request.urlretrieve(source, target, reporthook)

In [2]:
# if not os.path.isdir('aclImdb'):

#     with tarfile.open(target, 'r:gz') as tar:
#         tar.extractall()

In [3]:
# import pyprind
# import pandas as pd
# import os

# # change the `basepath` to the directory of the
# # unzipped movie dataset

# basepath = 'aclImdb'

# labels = {'pos': 1, 'neg': 0}
# pbar = pyprind.ProgBar(50000)
# df = pd.DataFrame()
# for s in ('test', 'train'):
#     for l in ('pos', 'neg'):
#         path = os.path.join(basepath, s, l)
#         for file in os.listdir(path):
#             with open(os.path.join(path, file), 
#                       'r', encoding='utf-8') as infile:
#                 txt = infile.read()
#             df = df.append([[txt, labels[l]]], 
#                            ignore_index=True)
#             pbar.update()
# df.columns = ['review', 'sentiment']

In [4]:
# import numpy as np

# np.random.seed(0)
# df = df.reindex(np.random.permutation(df.index))

In [5]:
# df.to_csv('movie_data.csv', index=False, encoding='utf-8')

In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import re

In [7]:
df = pd.read_csv('movie_data.csv', encoding='utf-8')
df.head(3)

review  sentiment
0  Based on an actual story, John Boorman shows t...          1
1  This is a gem. As a Film Four production - the...          1
2  I really like this show. It has drama, romance...          1

In [8]:
count = CountVectorizer()
docs = np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])
bag = count.fit_transform(docs)

In [15]:
count.get_feature_names()

['and', 'is', 'one', 'shining', 'sun', 'sweet', 'the', 'two', 'weather']

In [14]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


In [7]:
email_address = 'Please contact us at: support@datacamp.com'
match = re.search(r'([\w\.-]+)@([\w\.-]+)', email_address)
if match:
  print(match.group()) # The whole matched text
  print(match.group(1)) # The username (group 1)
  print(match.group(2)) # The host (group 2)

support@datacamp.com
support
datacamp.com


In [26]:
re.search(r'Back\\star', 'Back\star')

<re.Match object; span=(0, 9), match='Back\\star'>

In [22]:
re.search(r'Co.k.e', 'Cookie')

<re.Match object; span=(0, 6), match='Cookie'>