In [1]:
import pandas as pd
import numpy as np
import pymc3 as pm
import scipy.stats as stats
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
from plotly import tools
from plotly.graph_objs import *
from sushmit_plots import *

#### Code 3.1

In [2]:
PrPV = 0.95
PrPM = 0.01
PrV = 0.001
PrP = (PrPV*PrV + PrPM *(1 - PrV))
PrVP = PrPV * PrV/PrP
PrVP

0.08683729433272395

In [3]:
p_grid = np.linspace(start =0, stop = 1, num=20)
prior = np.repeat(1,20)
# compute likelihood at each value in grid
likelihood = stats.binom.pmf(6,9,p_grid)
posterior = likelihood * prior

# standardize the posterior, so it sums to 1
posterior = posterior / sum(posterior)
samples = np.random.choice(p_grid,p=posterior, size = int(1e4))

In [4]:
py.iplot(plot_scatter(x=[],y=samples))

### Creating the density plot

In [5]:

py.iplot(plot_density(samples=samples,PI =[0.25,0.5]))


In [6]:
sum(posterior[p_grid<0.5])

0.17072394266778282

In [7]:
sum(samples<0.5)/1e4

0.1681

In [8]:
sum((samples > 0.5) & (samples < 0.75)) / 1e4

0.63449999999999995

In [9]:
np.percentile(samples, 80)

0.73684210526315785

In [10]:
np.percentile(samples, [10,90])

array([ 0.47368421,  0.78947368])

### Code 3.1

In [11]:
p_grid = np.linspace(start =0, stop = 1, num=1000)
prior = np.repeat(1,1000)
# compute likelihood at each value in grid
likelihood = stats.binom.pmf(3,3,p_grid)
posterior = likelihood * prior

# standardize the posterior, so it sums to 1
posterior = posterior / sum(posterior)
samples = np.random.choice(p_grid,p=posterior, size = int(1e4))

### Code 3.2

In [12]:
np.percentile(samples, [25,75])

array([ 0.71271271,  0.93193193])

### Code 3.3

In [13]:
pm.hpd(samples, alpha=0.5)

array([ 0.84284284,  1.        ])

In [14]:
print(1)

1
