In [12]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np
sc = StandardScaler()

In [2]:
training_data = pd.read_csv(r'numerai_datasets\numerai_training_data.csv', header=0)

In [3]:
training_data.head()

id   era data_type  feature1  feature2  feature3  feature4  \
0  n2b2e3dd163cb422  era1     train   0.43487   0.44645   0.25802   0.37149   
1  n177021a571c94c8  era1     train   0.50038   0.39216   0.38394   0.51213   
2  n7830fa4c0cd8466  era1     train   0.47416   0.34143   0.39528   0.46337   
3  nc594a184cee941b  era1     train   0.48759   0.55903   0.43987   0.38834   
4  nc5ab8667901946a  era1     train   0.23433   0.55499   0.47849   0.56990   

   feature5  feature6  feature7   ...    feature42  feature43  feature44  \
0   0.62235   0.67451   0.68103   ...      0.52962    0.42439    0.51680   
1   0.36660   0.46911   0.68204   ...      0.51669    0.48445    0.57587   
2   0.72953   0.45962   0.47869   ...      0.41458    0.34804    0.29058   
3   0.44650   0.46389   0.70749   ...      0.28776    0.42881    0.55402   
4   0.64945   0.47152   0.62085   ...      0.64405    0.32416    0.33193   

   feature45  feature46  feature47  feature48  feature49  feature50  target  
0    0.46297    0.57426    0.57946    0.49646    0.48968    0.54194       1  
1    0.59860    0.67558    0.45577    0.80908    0.50287    0.61629       0  
2    0.51382    0.36389    0.80602    0.39253    0.41821    0.58679       0  
3    0.53695    0.48793    0.62432    0.52898    0.49009    0.49557       0  
4    0.58065    0.44587    0.47770    0.44020    0.47895    0.57978       0  

[5 rows x 54 columns]

In [18]:
list(training_data)
features = [f for f in list(training_data) if "feature" in f]
X= training_data.loc[:,features]
X_std = sc.fit_transform(X)
mean_vec = np.mean(X_std, axis=0)
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)

In [26]:
list(training_data)
features = [f for f in list(training_data) if "feature" in f]
X= training_data.loc[:,features]
X_std = sc.fit_transform(X)
cov_mat= np.cov(X_std.T)
eigen_vals,eigen_vecs = np.linalg.eig(cov_mat)
print(eigen_vals)

[7.57598173 5.52006472 4.80841239 3.82337527 3.51796433 3.13982217
 2.90386673 2.39856922 2.2604901  2.06930675 1.53824654 1.43265955
 1.35071865 1.10225056 0.84002011 0.78784368 0.66590328 0.55465855
 0.47728474 0.41044032 0.34721608 0.30132471 0.24495363 0.22242914
 0.18444855 0.16337953 0.15318215 0.14237137 0.10910198 0.09727967
 0.09677927 0.08364658 0.07925512 0.00880251 0.01051831 0.01449071
 0.01561732 0.02022528 0.02166343 0.02626325 0.02844558 0.03203085
 0.03811546 0.0419566  0.04511089 0.06577296 0.04981701 0.06165396
 0.05847882 0.05791692]


In [35]:
import numpy as np


# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
x = np.array([1, 2, 3])
print(x)
print(x.shape)
y=x.reshape((1, 3))
print(y)
print(y.shape)
z= x.reshape(3,1)
print(z)
print(z.shape)


[1 2 3]
(3,)
[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]
(3, 1)
