In [1]:
import pandas as pd
import torch
from torch import nn
from torch.nn import functional as F

## 5.1 Layers and Blocks

In [2]:
net = nn.Sequential(nn.Linear(20,256), nn.ReLU(),nn.Linear(256,10))
X = torch.rand(2,20)
print(X)
net(X)

tensor([[0.9499, 0.6279, 0.8557, 0.8877, 0.0437, 0.9693, 0.5835, 0.1182, 0.1458,
         0.2975, 0.2689, 0.6882, 0.4951, 0.2299, 0.0905, 0.8237, 0.0180, 0.4264,
         0.3097, 0.1798],
        [0.4766, 0.1842, 0.5198, 0.0858, 0.4872, 0.1636, 0.9780, 0.0068, 0.8623,
         0.7814, 0.8083, 0.5120, 0.0769, 0.9899, 0.9125, 0.9404, 0.0444, 0.9580,
         0.7412, 0.4275]])


tensor([[ 0.0780,  0.1358, -0.1807,  0.0482, -0.0598, -0.1324, -0.0425,  0.1576,
          0.0504,  0.2356],
        [ 0.0593, -0.1130, -0.0868, -0.2005,  0.0183, -0.1089, -0.1222,  0.0893,
          0.0199,  0.1092]], grad_fn=<AddmmBackward>)

In [3]:
class MLP(nn.Module):
    '''
    Notice how we are using forward
    '''
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.out = nn.Linear(256,10)
    def forward(self,X):
        return self.out(F.relu(self.hidden(X)))

In [4]:
mlp = MLP()
mlp(X)

tensor([[-1.1628e-01,  6.7285e-02, -5.4566e-02, -1.7556e-01,  1.6246e-01,
         -9.5139e-02,  9.2565e-02, -3.6533e-02,  1.1560e-01,  6.1935e-02],
        [ 5.9023e-02,  2.4318e-01,  7.7387e-02, -1.8918e-01,  9.3058e-06,
         -1.1765e-01,  1.4760e-01, -6.9179e-03,  5.6232e-02, -9.9254e-02]],
       grad_fn=<AddmmBackward>)